# Generated by Django 5.2.7 on 2025-10-23 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        default="AC Technology — Soluciones Integrales en Tecnología",
                        help_text="Título que aparece en Google (máx. 60 caracteres)",
                        max_length=60,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        default="Expertos en integración de redes, audio/video, domótica y seguridad para empresas, instituciones educativas y residencias.",
                        help_text="Descripción que aparece en Google (máx. 160 caracteres)",
                        max_length=160,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Palabras clave separadas por comas",
                        max_length=255,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="URL canónica del sitio (ej: https://actechnology.com.pe)",
                        verbose_name="URL Canónica",
                    ),
                ),
                (
                    "robots",
                    models.CharField(
                        choices=[
                            ("index, follow", "Index, Follow (Permitir todo)"),
                            (
                                "noindex, follow",
                                "No Index, Follow (No indexar, seguir enlaces)",
                            ),
                            (
                                "index, nofollow",
                                "Index, No Follow (Indexar, no seguir enlaces)",
                            ),
                            (
                                "noindex, nofollow",
                                "No Index, No Follow (Bloquear todo)",
                            ),
                        ],
                        default="index, follow",
                        max_length=50,
                        verbose_name="Robots Meta Tag",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="Título para redes sociales (si está vacío, usa meta_title)",
                        max_length=95,
                        verbose_name="OG Title",
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción para redes sociales (si está vacío, usa meta_description)",
                        max_length=200,
                        verbose_name="OG Description",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen para compartir en redes sociales (1200x630px recomendado)",
                        null=True,
                        upload_to="seo/",
                        verbose_name="OG Image",
                    ),
                ),
                (
                    "og_type",
                    models.CharField(
                        default="website",
                        help_text="Tipo de contenido (website, article, etc.)",
                        max_length=50,
                        verbose_name="OG Type",
                    ),
                ),
                (
                    "twitter_card",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary Large Image"),
                            ("app", "App"),
                            ("player", "Player"),
                        ],
                        default="summary_large_image",
                        max_length=50,
                        verbose_name="Twitter Card Type",
                    ),
                ),
                (
                    "twitter_site",
                    models.CharField(
                        blank=True,
                        help_text="@usuario de Twitter del sitio",
                        max_length=50,
                        verbose_name="Twitter Site",
                    ),
                ),
                (
                    "twitter_creator",
                    models.CharField(
                        blank=True,
                        help_text="@usuario de Twitter del creador",
                        max_length=50,
                        verbose_name="Twitter Creator",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Favicon del sitio (32x32px o 64x64px)",
                        null=True,
                        upload_to="seo/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "apple_touch_icon",
                    models.ImageField(
                        blank=True,
                        help_text="Icono para dispositivos Apple (180x180px)",
                        null=True,
                        upload_to="seo/",
                        verbose_name="Apple Touch Icon",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de Google Analytics (ej: G-XXXXXXXXXX o UA-XXXXXXXXX-X)",
                        max_length=50,
                        verbose_name="Google Analytics ID",
                    ),
                ),
                (
                    "google_site_verification",
                    models.CharField(
                        blank=True,
                        help_text="Código de verificación de Google Search Console",
                        max_length=100,
                        verbose_name="Google Site Verification",
                    ),
                ),
                (
                    "bing_site_verification",
                    models.CharField(
                        blank=True,
                        help_text="Código de verificación de Bing Webmaster Tools",
                        max_length=100,
                        verbose_name="Bing Site Verification",
                    ),
                ),
                (
                    "schema_organization_name",
                    models.CharField(
                        default="AC Technology",
                        max_length=100,
                        verbose_name="Nombre de la Organización (Schema)",
                    ),
                ),
                (
                    "schema_organization_logo",
                    models.URLField(
                        blank=True,
                        help_text="URL del logo de la organización",
                        verbose_name="Logo de la Organización (Schema)",
                    ),
                ),
                (
                    "author",
                    models.CharField(blank=True, max_length=100, verbose_name="Autor"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración SEO",
                "verbose_name_plural": "Configuración SEO",
            },
        ),
    ]
